version: "3"
services:
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "3000:80"
    redis:
        image: redis:latest
    postgres:
        restart: "always"
        build:
            dockerfile: Dockerfile.dev
            context: ./postgres
        environment:
            - "FILLA_DB_USER=docker"
            - "FILLA_DB_PASSWORD=postgres_password"
            - "FILLA_DB_DATABASE=multi_docker"
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /usr/app/node_modules
            - ./worker:/usr/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./api
        volumes:
            - /usr/app/node_modules
            - ./api:/usr/app
        environment:
            - SERVER_PORT=5000
            - PG_HOST=postgres
            - PG_PORT=5432
            - PG_USERNAME=docker
            - PG_PASSWORD=postgres_password
            - PG_DATABASE=multi_docker
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /usr/app/node_modules
            - ./client:/usr/app
