version: "3"
services:
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "3000:80"
    redis:
        image: redis:latest
    postgres:
        image: postgres:latest
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./api
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
        environment:
            - SERVER_PORT=5000
            - PG_HOST=postgres
            - PG_PORT=5432
            - PG_USERNAME=postgres
            - PG_PASSWORD=postgres_password
            - PG_DATABASE=docker_multi_container
